#!/usr/bin/env bash
# This Bash script installs nginx and configures a custom HTTP response header X-Served-By with the server hostname

# Install Nginx
apt-get update -y
apt-get install -y nginx

# Create root page
echo "Holberton School for the win!" > /var/www/html/index.html

# Get the hostname of the server
HOSTNAME=$(hostname)

# Add custom header with literal hostname
sed -i "s|server_name _;|server_name _;\n\tadd_header X-Served-By $HOSTNAME;|g" /etc/nginx/sites-available/default

# Test Nginx configuration
nginx -t

# Start or reload Nginx
if pgrep nginx >/dev/null 2>&1; then
    service nginx reload
else
    service nginx start
fi
