#!/usr/bin/env bash
# This Bash script installs and configures nginx to serve a page containing Holberton School

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx start
