#!/usr/bin/env bash
# This script installs Nginx on a Ubuntu server and configures the root page

# Update package lists
apt-get update -y

# Install Nginx
apt-get install -y nginx

# Write the required content to the root page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx using service
service nginx restart

